### ISSUE TITLE
Allow easy debug (or just give that as an option) - htmlentities

### ISSUE THREAD

**Issue by Froal** [meitar/libFetLife#7]
In doHttpRequest() of class FetLife:
```
$r = array();
        $this->cur_page = $r['body'] = curl_exec($ch); // Grab FetLife response body.
        $this->setCsrfToken($this->findCsrfToken($r['body'])); // Update on each request.
        $r['curl_info'] = curl_getinfo($ch);
        curl_close($ch);
        $this->cur_page = htmlentities($this->cur_page, ENT_COMPAT, 'UTF-8');
```
In all the getContentHtml methods:

```
// Add a parameter
getContentHtml ($pristine = true) 
```
```
$html = $pristine ? $html : htmlentities($html, ENT_COMPAT, 'UTF-8');
return $html;
```

**Comment by meitar** [comment]
At first glance, this (and the other suggestions you've supplied in other issues) look good, but do you think you can send me an actual patch instead of or in addition to opening issues for these suggestions? That way I can actually just branch and test without having to re-type or copy-and-paste everything you suggest by hand. Thanks!

For help on how to send me a patch, see [Using Pull Requests](https://help.github.com/articles/using-pull-requests/) in the GitHub help articles.

**Comment by ShanDaDF** [comment]
I’d like to, however my version of fetlifeLib is already outdated…
I’m gonna put it altogether and see if that works.
BTW: it’s all tested and live (on a website that I won’t mention here - if you got my message on your contact form on http://maybemaimed.com/ http://maybemaimed.com/, you should know which one).

**Comment by meitar** [comment]
I'm sorry, apparently your message was auto-spam'ed and I just now saw it. So, yes, I'm very glad you've chosen to patch upstream. Go ahead and send me a pull request at your convenience and I'll close out these tickets with each one. Thanks again for the patches. :)
